"""
Short drama playback resolver untuk iQIYI mobile API.
Menggunakan /video/play endpoint dengan s2=short_ply marker.
"""

# Language type mapping dari response
LANGUAGE_TYPE_MAP = {
    1: ("English", "en"),
    2: ("Mandarin Chinese", "zh-CN"),
    3: ("Cantonese", "zh-HK"),
    4: ("Japanese", "ja"),
    5: ("Korean", "ko"),
    6: ("Spanish", "es"),
    18: ("Indonesian", "id"),
    21: ("Thai", "th"),
    23: ("Vietnamese", "vi"),
    24: ("Malay", "ms"),
    26: ("Traditional Chinese", "zh-TW"),
    27: ("Turkish", "tr"),
    28: ("Russian", "ru"),
    30: ("Portuguese", "pt"),
}

# Standard mobile params template
MOBILE_PARAMS_BASE = {
    "app_k": "20911006a509e62d0901460c7b8b61a4",
    "app_v": "8.1.5",
    "app_t": "i18nvideo",
    "platform_id": "1070",
    "dev_os": "13",
    "dev_ua": "Redmi 5 Plus",
    "net_sts": "1",
    "scrn_scale": "1",
    "p_dolby": "0",
    "p_4k": "0",
    "secure_v": "1",
    "secure_p": "GPhone",
    "core": "1",
    "login_type": "1001",
    "customized": "1",
    "lang": "id_id",
    "app_lm": "id",
    "mod": "id",
    "timezone": "GMT+7",
    "pps": "0",
    "api_v": "7.7",
    "profile": "",
    "unlog_sub": "0",
    "cust_count": "",
    "scrn_sts": "0",
    "scrn_res": "1080,2160",
    "scrn_dpi": "400",
    "psp_vip": "0",
    "service_filter": "",
    "service_sort": "",
    "app_p": "gphone",
    "plist_id": "",
    "play_retry": "0",
    "content_type": "1,2,3",
    "play_res": "0",
    "play_core": "1",
    "sdk_v": "20000870",
    "abiFilter": "1",
    "sdk_build": "870.0.1190",
    "sdk_ctrl_v": "11.9.0",
    "net_ip": "",
    "ctl_dubi": "0",
    "src": "20",
    "rpage": "half_ply",
    "block": "bofangqi1",
    "s2": "short_ply",  # SHORT DRAMA MARKER
    "version": "8.1.5",
    "adid": "0",
    "rate": "4,8,16,512,",
    "is_bit64": "1",
    "req_times": "0",
}
